# Generated by Django 4.2.8 on 2023-12-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head',
            field=models.CharField(max_length=255),
        ),
    ]
