# Generated by Django 4.2.8 on 2024-01-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0002_alter_post_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, choices=[('AR', 'статья'), ('NE', 'новость')], default='NE', max_length=2),
        ),
    ]
