# Generated by Django 4.2.8 on 2024-01-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0003_alter_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sajt.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sajt.post')),
            ],
        ),
    ]
