# Generated by Django 4.2.8 on 2024-01-18 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0004_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='post',
        ),
        migrations.AddField(
            model_name='subscribers',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sajt.category'),
            preserve_default=False,
        ),
    ]
