# Generated by Django 4.2.8 on 2024-01-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0006_category_subscribers_delete_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
