# Generated by Django 4.2.8 on 2024-03-10 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sajt', '0008_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ru_RU',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sq',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers_ru_RU',
            field=models.ManyToManyField(blank=True, null=True, related_name='caregories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers_sq',
            field=models.ManyToManyField(blank=True, null=True, related_name='caregories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='author_ru_RU',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sajt.author'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_sq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sajt.author'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_ru_RU',
            field=models.ManyToManyField(null=True, through='sajt.PostCategory', to='sajt.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_sq',
            field=models.ManyToManyField(null=True, through='sajt.PostCategory', to='sajt.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='datetime_in_ru_RU',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='datetime_in_sq',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='head_ru_RU',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='head_sq',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rating_ru_RU',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rating_sq',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tekst_ru_RU',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tekst_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type_ru_RU',
            field=models.CharField(blank=True, choices=[('AR', 'статья'), ('NE', 'новость')], default='NE', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type_sq',
            field=models.CharField(blank=True, choices=[('AR', 'статья'), ('NE', 'новость')], default='NE', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='PostCategory_sq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sajt.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sajt.post')),
            ],
            options={
                'verbose_name': 'post category [sq]',
                'verbose_name_plural': 'post categorys [sq]',
                'db_table': 'sajt_postcategory_sq',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
        migrations.CreateModel(
            name='PostCategory_ru_RU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sajt.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sajt.post')),
            ],
            options={
                'verbose_name': 'post category [ru-RU]',
                'verbose_name_plural': 'post categorys [ru-RU]',
                'db_table': 'sajt_postcategory_ru_RU',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
    ]
